service: aws-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:851452142763:table/TaskTable
package:
  individually: true
  patterns:
    - "!*/**"

functions:
  hello:
    handler: src/index.hello
    package:
      patterns:
        - "src/index.js"
    events:
      - httpApi:
          path: /
          method: get
  createTask:
    handler: src/addTask.create
    package:
      patterns:
        - "src/addTask.js"
    events:
      - httpApi:
          path: /tasks
          method: post
resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH